// @lovable.dev/vite-tanstack-config already includes the following — do NOT add them manually
// or the app will break with duplicate plugins:
//   - tanstackStart, viteReact, tailwindcss, tsConfigPaths, nitro (build-only using cloudflare as a default target),
//     componentTagger (dev-only), VITE_* env injection, @ path alias, React/TanStack dedupe,
//     error logger plugins, and sandbox detection (port/host/strictPort).
// You can pass additional config via defineConfig({ vite: { ... }, etc... }) if needed.
//
// NOTE on the PWA service worker: it is intentionally NOT generated by a
// Vite plugin here. This project's Nitro build emits the real deployable
// client assets straight into `.output/public`, bypassing the `dist/client`
// directory a Vite-build-time PWA plugin would glob — that mismatch is why
// the service worker previously precached 0 files and never shipped to
// production at all. The service worker is now generated by
// `scripts/generate-sw.mjs`, run as a `postbuild` step (see package.json)
// once `.output/public` actually exists with the real hashed filenames.
import { defineConfig } from "@lovable.dev/vite-tanstack-config";

export default defineConfig({
  tanstackStart: {
    // Redirect TanStack Start's bundled server entry to src/server.ts (our SSR error wrapper).
    // nitro/vite builds from this
    server: { entry: "server" },
  },
});
